kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-moosefs-pvc-static
spec:
  storageClassName: moosefs-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
